language: ruby

rvm:
  - 2.0.0

branches:
  only:
      - master

#ibefore_script:
#  - mysql -e 'create database itedd_test'

script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

bundler_args: "--without development production"
