development:
  adapter: mysql2
  encoding: utf8
  database: itedd_development
  username: root
  password:
  socket: /opt/lampp/var/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: itedd_test
  username: root
  password:
  socket: /opt/lampp/var/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: itedd
  username: itedd
  password: <password>
  host: 127.0.0.1
  port: 3306
